# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01122bc14e662961a48dbc083a4b5de5a3d07f09fbbb3b7cb5d3ad49f6bdce271ef60f1e13ed040ffb764e8d04b44c02c451e738a6f3881410bc9676d43636a

test:
  secret_key_base: 7678557f49122f28be3ead62f1a84e60560516ac36df267405ec47631619ea85c3766a37432afce606ae869274c8c27db009c32c44cfe7cf579416a641d338bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
